apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: cloudnova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: ahmedsabra/cloudnova-cart-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "db-cart"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: cloudnova
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 8080
      targetPort: 8080
